### ISSUE TITLE
How did you install giscus?

### ISSUE THREAD

**Issue by imjimit07** [karanpratapsingh/portfolio#45]
I saw your website and i also wanted to install giscus but i dont know how did you do it?

**Comment by karanpratapsingh** [comment]
Hey @imjimit07, you first need to configure [giscus](https://giscus.app/) from here then add the [giscus app](https://github.com/apps/giscus) to your repository. You can follow [this article](https://zhauniarovich.com/post/2021/2021-06-giscus/).
