### ISSUE TITLE
Newsletter Configuration

### ISSUE THREAD

**Issue by kaizendae** [karanpratapsingh/portfolio#48]
Hello Karan
I have a question about the newsletter.
I added convertkit env vars and enabled it in siteMetaData `provider: 'convertkit',` where and when does the form appear how can I make sure it is working?

**Comment by karanpratapsingh** [comment]
Hi @kaizendae, refer to the [original template](https://github.com/timlrx/tailwind-nextjs-starter-blog) my site uses since I don't utilize the newsletter functionality.
